"""Assemble output/results_summary.md from the tables written by run_all.py (the numbers the protocol, model/approach
and README templates need, mapped by the section table of docs/05)."""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

import analysis_config as C

OUT = C.OUT; TAB = OUT / "tables"


def _csv(name):
    p = TAB / name
    return pd.read_csv(p) if p.exists() else None


def _md(df, cols=None, digits=3):
    if df is None or not len(df):
        return "_not available_\n"
    d = df if cols is None else df[[c for c in cols if c in df.columns]]
    return d.round(digits).to_markdown(index=False) + "\n"


def run():
    res = json.load(open(OUT / "metrics.json"))
    m = _csv("metrics.csv"); sw = _csv("label_sweep_5y.csv"); sg = _csv("subgroups_5y.csv"); pol = _csv("policy_metrics.csv")
    ce = _csv("oracle_ceiling.csv"); aud = _csv("oracle_definition_audit.csv"); rv = _csv("oracle_reference_value.csv"); ms = _csv("oracle_mechanism_shifts.csv"); ss = _csv("oracle_sample_size.csv")
    s23 = _csv("secondary_stage2_to_stage3.csv"); bvf = _csv("secondary_bvf_reintervention_cif.csv"); slope = _csv("secondary_gradient_slope.csv")
    pm = TAB / "parsimonious_model.json"; pars = json.load(open(pm)) if pm.exists() else None
    u = res["usefulness"]
    lines = ["# Results summary (generated by summarise.py)\n",
             f"Test set: {res['n_test_valves']} valves, {res['n_test_instances']} landmark instances, {res['n_test_implant']} implant-time instances (valve-level split; CIs by valve bootstrap, B = {C.BOOT_B}).\n",
             "## 1. Usefulness thresholds (docs/03 section 0), primary landmark model, confirmed VARC-3 label, 5 y\n",
             f"- time-dependent AUC {u['AUC_5y']:.3f} (threshold 0.75: {'PASS' if u['AUC_ge_0.75'] else 'FAIL'}); cause-specific C {u['C_5y']:.3f} (0.70: {'PASS' if u['C_ge_0.70'] else 'FAIL'}); calibration slope {u['calib_slope_5y']:.2f} (0.8-1.2: {'PASS' if u['slope_in_0.8_1.2'] else 'FAIL'})\n"]
    if m is not None:
        cn = m[(m.model == "dth_full") & (m.subset == "currently_negative") & (m.tau == 5.0)]
        if len(cn):
            r = cn.iloc[0]; lines.append(f"- on currently-negative echoes (where the surveillance decision is taken): AUC {r.AUC:.3f} [{r.AUC_lo:.3f}, {r.AUC_hi:.3f}], C {r.C_trunc:.3f}, slope {r.calib_slope:.2f}\n")
        lines += ["\n### Model comparison\n", _md(m, ["model", "subset", "tau", "n_eligible", "n_cases", "AUC", "AUC_lo", "AUC_hi", "C_trunc", "Brier", "calib_slope"])]
    lines += ["\n## 2. Label sweep at 5 y (same instances and predictions; protocol section 4 ground truth, approach section 7)\n", _md(sw, ["label", "AUC", "n_cases"])]
    if ce is not None: lines += ["\n### Achievable ceiling (oracle-only)\n", _md(ce)]
    lines += ["\n## 3. Subgroups and fairness (protocol section 5 / 6)\n", _md(sg, ["factor", "level", "n_instances", "n_cases", "AUC", "C_trunc", "calib_slope"])]
    if pars: lines += ["\n## 4. Parsimonious model (approach section 3 feature selection)\n", f"{len(pars['parsimonious_features'])} features, AUC {pars['AUC_5y']:.3f} vs full {pars['full_AUC_5y']:.3f}: `{', '.join(pars['parsimonious_features'])}`\n",
                       "SHAP top 10: " + ", ".join(f"{d['feature']} ({d['mean_abs_shap']:.3f})" for d in pars["shap_top10"]) + "\n"]
    if aud is not None: lines += ["\n## 5. Definition audit against the latent truth (secondary objective 4)\n", _md(aud)]
    if rv is not None: lines += ["\n## 6. Value of the 30-day reference echo\n", _md(rv)]
    if ms is not None: lines += ["\n## 7. Robustness to mechanism shifts (approach section 4 / 7)\n", _md(ms)]
    if ss is not None: lines += ["\n## 8. Simulation-based sample size (protocol section 5)\n", _md(ss)]
    if pol is not None:
        lines += ["\n## 9. Surveillance policies (secondary objective 2; approach sections 5-6)\n",
                  _md(pol, ["policy", "tau", "echoes_per_patient_decade", "detection_rate", "confirmed_delay_mean_y", "confirmed_delay_p90_y", "stage3_seen_while_stage2_share", "urgent_share", "false_positive_reinterventions", "echo_reduction_vs_guideline_pct", "extra_delay_mean_months", "extra_delay_p90_months", "passes_section0", "echo_reduction_vs_guideline_confirm_pct", "extra_delay_vs_confirm_mean_months", "extra_delay_vs_confirm_p90_months", "passes_section0_vs_confirm"])]
        ok = pol[pol.passes_section0 == True] if "passes_section0" in pol else pol.iloc[0:0]
        if len(ok):
            best = ok.sort_values("echoes_per_patient_decade").iloc[0]
            lines.append(f"\nBest policy meeting the section-0 criterion: `{best.policy}` with {best.echo_reduction_vs_guideline_pct:.0f}% fewer echoes and {best.extra_delay_mean_months:+.1f} months mean / {best.extra_delay_p90_months:+.1f} months P90 delay vs the guideline.\n")
    if s23 is not None: lines += ["\n## 10. Secondary endpoints (secondary objective 3)\n", _md(s23), _md(bvf), _md(slope)]
    (OUT / "results_summary.md").write_text("".join(lines))
    print("".join(lines)[:6000])


if __name__ == "__main__":
    run()
